resources:
- name: solder_java
  type: git
  source:
    branch: master
    uri: https://github.com/venkatpathy/solder_java.git

jobs:
- name: Unit Tests
  public: false
  plan:
    - get: solder_java
      trigger: true
    - task: Run Unit Tests
      file: solder_java/ci/task_run_tests.yml

- name: Build
  public: false
  plan:
    - get: solder_java
      passed: [Unit Tests]
      trigger: true
    - task: Build Code
      file: solder_java/ci/task_buildcode.yml